<?php
namespace app\admin\controller;
use think\Request;

class About extends Common{
    protected $db;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db=new \app\admin\model\About();
    }

    public function index(){
        $content=$this->db->index();
        return $this->fetch('',[
           'content'=>$content
        ]);
    }
    public function edit(Request $request){
        if($request->isPost()){
            $res=$this->db->edit(input('post.'));
            if($res){
                $this->success('更新内容成功');
            }else{
                $this->error('更新内容失败');
            }
        }
    }
}