<?php
namespace app\admin\controller;
use think\Controller;
use think\Request;

class Login extends Controller{
    protected $db;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db=new \app\admin\model\Login();
    }
    public function index(Request $request){
        if($request->isPost()){
            if(!captcha_check(input('post.verifyCode'))) {
                // 校验失败
                $this->error('验证码不正确');
            }
            $res=$this->db->login(input('post.'));
            if($res){
                $this->success('登录成功','/admin/index');exit;
            }else{
                $this->error("登录失败");exit;
            }
        }
        if(session('?admin_id')){
            return redirect('/admin/index');
        }
        return $this->fetch();
    }
    public function logout(){
        session(null);
        return $this->redirect('/admin/login');
    }
}