<?php
namespace app\admin\controller;
use think\Request;

class ProductImage extends Common{
    protected $db;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db=new \app\admin\model\ProductImage();
    }
    public function del(Request $request){
        $id=intval(input('get.img_id'));
        $res=$this->db->del($id);
        unlink($_SERVER["DOCUMENT_ROOT"].'/uploads/'.$res['src']);
        return $res;
    }
}