<?php
namespace app\index\controller;
use think\Controller;
use think\Model;
use think\Request;

class Index extends Controller
{
    protected $product_db;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->product_db=new \app\index\model\Product();
    }
    public function index()
    {
        $discount=$this->product_db->getDiscount();
        $style=Model('ProductStyle')->getShowIndex;
        $new_style=$this->product_db->getShowProduct($style);
        $recommend=$this->product_db->getRecommend();
        $information=Model('Information')->getInformation();
        $this->assign('information',$information);
        $this->assign('recommend',$recommend);
        $this->assign('newStyle',$new_style);
        $this->assign('discount',$discount);
        return $this->fetch();
    }
    public function agentAdd(Request $request){
        if($request->isPost()){
            $content='姓名：'.input('post.name')."<br>手机：".input('post.mobile');
            \phpmailer\Email::send('huanggengming1@163.com', '网站有新的代理申请了！', $content);/*huanggengming1*/
            $res=Model('Agent')->db()->insert(input('post.'));
            return $res;
        }
    }
}
