<?php

namespace app\index\controller;

use think\Controller;
use think\Request;

class Information extends Controller
{
    protected $db;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db=new \app\index\model\Information();
    }

    public function index()
    {
        $category=model('InformationCategory')->db()->select();
        $information=$this->db->index();
        return $this->fetch('',[
            'category'=>$category,
            'information'=>$information
        ]);
    }
    public function category(Request $request){
        $id=intval(input('get.id'));
        if(!$id||!($request->isGet())){
            return "<script>history.go(-1)</script>";
        }
        $category=model('InformationCategory')->db()->select();
        $information=$this->db->category($id);
        return $this->fetch('index',[
            'category'=>$category,
            'information'=>$information
        ]);
    }
    public function show(Request $request){
        $id=intval(input('get.id'));
        if(!$id||!($request->isGet())){
            return "<script>history.go(-1)</script>";
        }
        $info=$this->db->find($id);
        return $this->fetch('',[
            'info'=>$info
        ]);
    }
}