<?php
namespace app\index\controller;
use think\Controller;
use think\Request;

class Introduce extends Controller{
    protected $db;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db=new \app\index\model\Introduce();
    }

    public function index(){
        $intro=$this->db->find(1);
        return $this->fetch('',[
           'intro'=>$intro
        ]);
    }
    public function join(){
        $join=$this->db->find(2);
        return $this->fetch('',[
            'join'=>$join
        ]);
    }
    public function add(Request $request){
        if($request->isPost()){
            $date=input('post.');
            $name=$date['name'];
            $mobile=$date['mobile'];
            $email=$date['email']?$date['email']:'未填写邮箱';
            $content=$date['content']?$date['content']:'未填写申请内容';
            $msg='姓名：'.$name.'<br>手机：'.$mobile.'<br>邮箱：'.$email.'<br>申请内容:<br>'.$content;
            \phpmailer\Email::send('huanggengming1@163.com', '网站有新的代理申请了！', $msg);/*huanggengming1*/
            if(model('Agent')->db()->insert(input('post.'))){
                return true;
            }
        }
    }
}