<?php
namespace app\index\controller;
use think\Controller;
use think\Request;

class Product extends Controller{
    protected $db;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db= new \app\index\model\Product();
    }

    public function index(){
        $style=model('ProductStyle')->db()->select();
        $product=model('Product')
            ->db()
            ->where('status','<>',0)
            ->order('update_time desc')
            ->paginate(16);
        return $this->fetch('',[
            'style'=>$style,
            'product'=>$product
        ]);
    }
    public function all(){
        /*写入cookie 判断cookie给选项卡添加active类*/
        $style=model('ProductStyle')->db()->select();
        $product=model('Product')
            ->db()
            ->where('status','<>',0)
            ->order('update_time desc')
            ->paginate(16);
        return $this->fetch('index',[
            'style'=>$style,
            'product'=>$product
        ]);
    }
    public function recommend(){
        $style=model('ProductStyle')->db()->select();
        $product=model('Product')->db()
            ->where('status',2)
            ->order('update_time desc')
            ->paginate(16);;
        return $this->fetch('index',[
            'style'=>$style,
            'product'=>$product
        ]);
    }
    public function discount(){
        $style=model('ProductStyle')->db()->select();
        $product=model('Product')->db()
            ->where('discount',['>',0],['<',1],'and')
            ->where('status','<>',0)
            ->order('update_time desc')
            ->paginate(16);;
        return $this->fetch('index',[
            'style'=>$style,
            'product'=>$product
        ]);
    }
    public function style(Request $request){
        $id=intval(input('get.id'));
        if(!$id||!($request->isGet())){
            return "<script>history.go(-1)</script>";
        }
        $style=model('ProductStyle')->db()->select();
        $product=model('Product')->db()
            ->where('product_style_id',$id)
            ->where('status','<>',0)
            ->order('update_time desc')
            ->paginate(16);;
        return $this->fetch('index',[
            'style'=>$style,
            'product'=>$product
        ]);
    }
    public function productShow(Request $request){
        $id=intval(input('get.id'));
        $product=$this->db->getProductById($id);
        return $this->fetch('',[
            'product'=>$product
        ]);
    }
}